### ISSUE TITLE
 License Information

### ISSUE THREAD

**Issue by unkn0wn-us3r** [Sjord/jwtcrack#6]
Hi,
Really great work Sjoerd! I really appreciate the project and the efforts you have put into it. We would like to use the project for a commercial training online/classroom. So, I just wanted to clarify, if we acknowledge the source, would that be sufficient and covered under the terms of use?

**Comment by Sjord** [comment]
How are you going to use it exactly? Would licensing this under GNU AGPLv3 work for you?

**Comment by unkn0wn-us3r** [comment]
Hi Sjoerd,
Thanks for a quick reply. We would like to use the project for a commercial training online/classroom.
Yes, this license would be perfect for our use-case. Could you please add the above mentioned license to the repository?

Thanks.

**Comment by Sjord** [comment]
I have added a LICENSE file that indicates that this project is licensed under GNU Affero General Public License v3.0.

**Comment by unkn0wn-us3r** [comment]
Great! Thanks a lot Sjord. We really appreciate your support.
